;设置规则标志位
ruleset=中国大陆,[]GEOIP,CN
ruleset=全球,[]MATCH
;设置规则标志位

;设置分组标志位
custom_proxy_group=全球`select`[]🚀自动选择最快`[]🍃故障自动转移`[]🎯全球直连`[]🛑全球拦截`.*
custom_proxy_group=中国大陆`select`[]🚀自动选择最快`[]🍃故障自动转移`[]🎯全球直连`[]🛑全球拦截`.*
custom_proxy_group=🎯全球直连`select`[]DIRECT`
custom_proxy_group=🛑全球拦截`select`[]REJECT
custom_proxy_group=🚀自动选择最快`url-test`.*`http://127.0.0.1:2061/generate_204`300
custom_proxy_group=🍃故障自动转移`fallback`[]🚀自动选择最快`.*`http://127.0.0.1:2061/generate_204`300

;设置分组标志位
