user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

stream {
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    client_max_body_size 100M;

    map $http_x_real_ip $client_ip {
        default $http_x_real_ip;
        ""      $remote_addr;
    }




    server {
        listen [::]:80 ipv6only=off;

        index  index.html index.htm ;
        root /wwwroot/admin-web;

        location /adminapi/ {
               proxy_pass http://nodami-server:8200/;
               include ./proxy_headers.conf;
        }

        location /client {
               proxy_pass http://nodami-server:8200;
               include ./proxy_headers.conf;
        }

         location /terminal {
               proxy_pass http://nodami-server:8200;
               include ./proxy_headers.conf;
        }



        location /agent {
               proxy_pass http://nodami-server:8200;
               include ./proxy_headers.conf;
        }

        location /down/ {
               alias /wwwroot/agent_server/;
        }

        location / {
             try_files $uri $uri/ /index.html;
        }

        location ~ /\.ht {
            deny all;
        }

        location ~ ^/(application|runtime|config|vendor)/ {
            deny all;
            return 404;
        }
    }



}
