// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.2
// source: frp.proto

package commonInfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrpcInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     int32  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`        // 节点ID
	ServerAddr string `protobuf:"bytes,2,opt,name=serverAddr,proto3" json:"serverAddr,omitempty"` // Frps 服务端IP
	LocalPort  int32  `protobuf:"varint,3,opt,name=localPort,proto3" json:"localPort,omitempty"`  // 穿透本地端口
	// int32 remotePort = 4;    // 穿透服务端端口
	Role string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"` //server //visitor
}

func (x *FrpcInfo) Reset() {
	*x = FrpcInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrpcInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrpcInfo) ProtoMessage() {}

func (x *FrpcInfo) ProtoReflect() protoreflect.Message {
	mi := &file_frp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrpcInfo.ProtoReflect.Descriptor instead.
func (*FrpcInfo) Descriptor() ([]byte, []int) {
	return file_frp_proto_rawDescGZIP(), []int{0}
}

func (x *FrpcInfo) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *FrpcInfo) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *FrpcInfo) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *FrpcInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_frp_proto protoreflect.FileDescriptor

var file_frp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x66, 0x72, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x72, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x74, 0x0a, 0x08, 0x46, 0x72, 0x70, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_frp_proto_rawDescOnce sync.Once
	file_frp_proto_rawDescData = file_frp_proto_rawDesc
)

func file_frp_proto_rawDescGZIP() []byte {
	file_frp_proto_rawDescOnce.Do(func() {
		file_frp_proto_rawDescData = protoimpl.X.CompressGZIP(file_frp_proto_rawDescData)
	})
	return file_frp_proto_rawDescData
}

var file_frp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frp_proto_goTypes = []interface{}{
	(*FrpcInfo)(nil), // 0: frpInfo.FrpcInfo
}
var file_frp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frp_proto_init() }
func file_frp_proto_init() {
	if File_frp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrpcInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frp_proto_goTypes,
		DependencyIndexes: file_frp_proto_depIdxs,
		MessageInfos:      file_frp_proto_msgTypes,
	}.Build()
	File_frp_proto = out.File
	file_frp_proto_rawDesc = nil
	file_frp_proto_goTypes = nil
	file_frp_proto_depIdxs = nil
}
