// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package commonInfo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClashSpeedClient is the client API for ClashSpeed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClashSpeedClient interface {
	SpeedTest(ctx context.Context, in *Proxie, opts ...grpc.CallOption) (*Response, error)
	URLTest(ctx context.Context, in *Proxie, opts ...grpc.CallOption) (*Response, error)
}

type clashSpeedClient struct {
	cc grpc.ClientConnInterface
}

func NewClashSpeedClient(cc grpc.ClientConnInterface) ClashSpeedClient {
	return &clashSpeedClient{cc}
}

func (c *clashSpeedClient) SpeedTest(ctx context.Context, in *Proxie, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/speed.ClashSpeed/SpeedTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clashSpeedClient) URLTest(ctx context.Context, in *Proxie, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/speed.ClashSpeed/URLTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClashSpeedServer is the server API for ClashSpeed service.
// All implementations must embed UnimplementedClashSpeedServer
// for forward compatibility
type ClashSpeedServer interface {
	SpeedTest(context.Context, *Proxie) (*Response, error)
	URLTest(context.Context, *Proxie) (*Response, error)
	mustEmbedUnimplementedClashSpeedServer()
}

// UnimplementedClashSpeedServer must be embedded to have forward compatible implementations.
type UnimplementedClashSpeedServer struct {
}

func (UnimplementedClashSpeedServer) SpeedTest(context.Context, *Proxie) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpeedTest not implemented")
}
func (UnimplementedClashSpeedServer) URLTest(context.Context, *Proxie) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method URLTest not implemented")
}
func (UnimplementedClashSpeedServer) mustEmbedUnimplementedClashSpeedServer() {}

// UnsafeClashSpeedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClashSpeedServer will
// result in compilation errors.
type UnsafeClashSpeedServer interface {
	mustEmbedUnimplementedClashSpeedServer()
}

func RegisterClashSpeedServer(s grpc.ServiceRegistrar, srv ClashSpeedServer) {
	s.RegisterService(&ClashSpeed_ServiceDesc, srv)
}

func _ClashSpeed_SpeedTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proxie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClashSpeedServer).SpeedTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/speed.ClashSpeed/SpeedTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClashSpeedServer).SpeedTest(ctx, req.(*Proxie))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClashSpeed_URLTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proxie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClashSpeedServer).URLTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/speed.ClashSpeed/URLTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClashSpeedServer).URLTest(ctx, req.(*Proxie))
	}
	return interceptor(ctx, in, info, handler)
}

// ClashSpeed_ServiceDesc is the grpc.ServiceDesc for ClashSpeed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClashSpeed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speed.ClashSpeed",
	HandlerType: (*ClashSpeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpeedTest",
			Handler:    _ClashSpeed_SpeedTest_Handler,
		},
		{
			MethodName: "URLTest",
			Handler:    _ClashSpeed_URLTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "speed.proto",
}
