// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.28.3
// source: speed.proto

package commonInfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res int32 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_speed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_speed_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetRes() int32 {
	if x != nil {
		return x.Res
	}
	return 0
}

type Proxie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proxies string `protobuf:"bytes,1,opt,name=proxies,proto3" json:"proxies,omitempty"`
	Groups  string `protobuf:"bytes,2,opt,name=groups,proto3" json:"groups,omitempty"`
	Url     string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Proxie) Reset() {
	*x = Proxie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proxie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxie) ProtoMessage() {}

func (x *Proxie) ProtoReflect() protoreflect.Message {
	mi := &file_speed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxie.ProtoReflect.Descriptor instead.
func (*Proxie) Descriptor() ([]byte, []int) {
	return file_speed_proto_rawDescGZIP(), []int{1}
}

func (x *Proxie) GetProxies() string {
	if x != nil {
		return x.Proxies
	}
	return ""
}

func (x *Proxie) GetGroups() string {
	if x != nil {
		return x.Groups
	}
	return ""
}

func (x *Proxie) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_speed_proto protoreflect.FileDescriptor

var file_speed_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x22, 0x1c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72,
	0x65, 0x73, 0x22, 0x4c, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x32, 0x68, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x2d,
	0x0a, 0x09, 0x53, 0x70, 0x65, 0x65, 0x64, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x1a, 0x0f, 0x2e, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a,
	0x07, 0x55, 0x52, 0x4c, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x2e, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x1a, 0x0f, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x64, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x0a, 0x19, 0x69, 0x6f,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0c, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_speed_proto_rawDescOnce sync.Once
	file_speed_proto_rawDescData = file_speed_proto_rawDesc
)

func file_speed_proto_rawDescGZIP() []byte {
	file_speed_proto_rawDescOnce.Do(func() {
		file_speed_proto_rawDescData = protoimpl.X.CompressGZIP(file_speed_proto_rawDescData)
	})
	return file_speed_proto_rawDescData
}

var file_speed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_speed_proto_goTypes = []interface{}{
	(*Response)(nil), // 0: speed.Response
	(*Proxie)(nil),   // 1: speed.Proxie
}
var file_speed_proto_depIdxs = []int32{
	1, // 0: speed.ClashSpeed.SpeedTest:input_type -> speed.Proxie
	1, // 1: speed.ClashSpeed.URLTest:input_type -> speed.Proxie
	0, // 2: speed.ClashSpeed.SpeedTest:output_type -> speed.Response
	0, // 3: speed.ClashSpeed.URLTest:output_type -> speed.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_speed_proto_init() }
func file_speed_proto_init() {
	if File_speed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_speed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_speed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proxie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_speed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_speed_proto_goTypes,
		DependencyIndexes: file_speed_proto_depIdxs,
		MessageInfos:      file_speed_proto_msgTypes,
	}.Build()
	File_speed_proto = out.File
	file_speed_proto_rawDesc = nil
	file_speed_proto_goTypes = nil
	file_speed_proto_depIdxs = nil
}
